### ISSUE TITLE
question about sge

### ISSUE THREAD

**Issue by SaintLogos1234** [implus/PytorchInsight#11]
I read resnet_sge.py code, I find that weight and bias initial code is :
```
self.weight   = Parameter(torch.zeros(1, groups, 1, 1))
self.bias     = Parameter(torch.ones(1, groups, 1, 1))
```
That is not wrong？should not be the following code：
```
self.weight   = Parameter(torch.ones(1, groups, 1, 1))
self.bias     = Parameter(torch.zeros(1, groups, 1, 1))
```

**Comment by implus** [comment]
See the ablation study in our paper. This initialization will lead to slightly better results.
