### ISSUE TITLE
About global statistical feature

### ISSUE THREAD

**Issue by zsano1** [implus/PytorchInsight#12]
https://github.com/implus/PytorchInsight/blob/a2d9ffb289b4889957e882478e750d947ecb3208/classification/models/imagenet/resnet_sge.py#L10
As in the paper, the global statistical feature, i.e. "semantic vector g that this group learns to represent" is a vector which makes sense that dot product can represent the similarity. But in the code, it seems to be a number. And I think the larger x_i is, the larger c_i is? How it can measure the similarity between x and g?

**Comment by implus** [comment]
``But in the code, it seems to be a number''. Please learn pytorch API/document carefully first, especially for nn.AdaptiveAvgPool2d(1). Thanks!

**Comment by zsano1** [comment]
@implus Sorry about the ambiguity of expression, but what I mean is in my oninion, what we need is like Capsne PrimaryCapsules, output is a 8-dimension vector (input shape: 20*20*256, output shape: 32*6*6*8, this 8 makes the output capsule a vector, not a scalar). But in your code, i think ave_pool is a scalar(output: b*groups,-1,1,1), and the greater x(shape: b*groups,-1,h,w) is, the greater xn(xn=x*ave_pool) is. I think to represent the similarity, we should add a dimension to form a vector?

**Comment by implus** [comment]
xiang.li.implus@njust.edu.cn

用中文邮箱发我吧。。。英文描述太confusing了。。。抱歉不太清楚在问什么~另外建议把所有参数都对应成具体的数字实例。
