### ISSUE TITLE
About the kernel size in resnet_sk

### ISSUE THREAD

**Issue by yuhuixu1993** [implus/PytorchInsight#14]
hi, @implus , thanks for sharing the codes. I have a question that the two convolutions in resnet_sk are all 3x3 conv. While your paper says they are with different kernel-size or different dilation sizes?

**Comment by 13952522076** [comment]
> hi, @implus , thanks for sharing the codes. I have a question that the two convolutions in resnet_sk are all 3x3 conv. While your paper says they are with different kernel-size or different dilation sizes?

Maybe I can answer this question. As SKNet indicated, the kernel size of second conv could be any size. In this code, it is 3x3 but grouped. Also, u can adopt 3x3 conv with dilation 2 to simulate a 5x5 conv.

**Comment by implus** [comment]
Yes, it can be any size and in this project, we slightly modify the SK operation because we need to base on ResNet-like architecture. The original SK paper is mainly based on ResNeXt-like architecture.
