### ISSUE TITLE
你好，Shufflenetv2的预训练模型可以发一份吗，下载不了了

### ISSUE THREAD

**Issue by djsFFF** [implus/PytorchInsight#15]
邮箱1210090743@qq.com，感激不尽！！！

**Comment by implus** [comment]
I can download from the provided link successfully. Maybe you can try some VPN ?

**Comment by djsFFF** [comment]
I used vpn. Just click on the link and the Google Cloud Disk prompts me that I have no access rights.

**Comment by implus** [comment]
ok， I will send one~

**Comment by djsFFF** [comment]
Thank you very much!!!
