### ISSUE TITLE
Other links to download pre-trained models?

### ISSUE THREAD

**Issue by thomhert** [implus/PytorchInsight#4]
Hi!
Thank you for sharing your codes and creating this repo.
Wondering if you could provide other links (not baidu) to download pre-trained models?
I have tried to download some models, but failed. Really appreciate if you do so.

**Comment by zimenglan-sysu-512** [comment]
it's hard to download the pre-trained model from baidu yun in linux system, so can you provide other download links for us, like google cloud?

**Comment by implus** [comment]
We will add GoogleDrive links. Uploading them onto GoogleDrive is very slow for us now... We will update them all once the uploading is finished. Thanks~

**Comment by implus** [comment]
@shiyuanyin 

Please refer to the closed issue #9 , thanks~

**Comment by QuantScientist** [comment]
Hello,
Please .... google drive links? 
Thanks,.

**Comment by implus** [comment]
Hi, all the models are available in GoogleDrive~
