### ISSUE TITLE
about the settings of mean, std, and to_bgr255

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [implus/PytorchInsight#8]
hi @implus 
the settings of mean, std, and to_bgr255 in SGE-Net is “mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], to_bgr255=False”？

**Comment by implus** [comment]
yes~

**Comment by lxtGH** [comment]
Hi! @implus Thanks for your released code. I wonder how to reproduce the results of SGE-ResNet101 ??
Using which .py files ?

**Comment by implus** [comment]
@lxtGH  Hi，sorry for the late reply. 
you can simply use:
python -W ignore imagenet.py -a sge_resnet101 --data /pth/to/imagenet1k/ --epochs 100 --schedule 30 60 90 --gamma 0.1 -c checkpoints/imagenet/sge_resnet101 --gpu-id 0,1,2,3,4,5,6,7

**Comment by shiyuanyin** [comment]
@implus 
hi 
我想请教下这里的实际细节，我想改成  mxnet,这里的组概念不是很清楚，然后这里的各种shape操作，
def forward(self, x): # (b, c, h, w)
        b, c, h, w = x.size()
        x = x.view(b * self.groups, -1, h, w)  ##reshape
        xn = x * self.avg_pool(x)  # x * global pooling(h,w change 1)
        xn = xn.sum(dim=1, keepdim=True) #(b,1,h,w)
        t = xn.view(b * self.groups, -1)  
        t = t - t.mean(dim=1, keepdim=True)  
        std = t.std(dim=1, keepdim=True) + 1e-5
        t = t / std  # normalize  -mean/std
        t = t.view(b, self.groups, h, w)
        t = t * self.weight + self.bias
        t = t.view(b * self.groups, 1, h, w)
        x = x * self.sig(t)   #in order to sigmod facter,this is group factor (0-1)
        x = x.view(b, c, h, w) #get to varying degrees of importance,Restoration dimension
        return x
