### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by ztyxd** [implus/PytorchInsight#9]
I have download pretrained model : resnet-sge_101.pth.tar，
but I cannot open extract this file in both windows and ubuntu.
Can U give me some suggestions about this question or other links of the pretrained models?
Thanks!

**Comment by implus** [comment]
You do not need to extract this file. Please refer to https://github.com/implus/PytorchInsight/blob/master/classification/pretrain_test.md

Simply use ``python -W ignore imagenet.py -a sge_resnet101 --data /yourpath/imagenet1k/ --gpu-id 0 -e --resume ../pretrain/sge_resnet101.pth.tar'' will be ok.

**Comment by ztyxd** [comment]
Thanks a lot，I solve this problem.
